[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"
authors = ["Cunyue"]
description = "A simple CLI tool for search the word in file. Just for fun!"



[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
